C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.4.2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapcshm (cshmf2pywrap, cd_py, cr_py, na_py, 
     &mt_py)
      external cshm
      integer na_py
      integer mt_py
      real(kind=8) cd_py(na_py,3)
      real(kind=8) cr_py(na_py,3)
      real(kind=8) cshmf2pywrap
      real(kind=8)  cshm
      cshmf2pywrap = cshm(cd_py, cr_py, na_py, mt_py)
      end


      subroutine f2pywrapcshm_fix (cshm_fixf2pywrap, cd_py, cr_py,
     & na_py, mt_py)
      external cshm_fix
      integer na_py
      integer mt_py
      real(kind=8) cd_py(na_py,3)
      real(kind=8) cr_py(na_py,3)
      real(kind=8) cshm_fixf2pywrap
      real(kind=8)  cshm_fix
      cshm_fixf2pywrap = cshm_fix(cd_py, cr_py, na_py, mt_py)
      end


      subroutine f2pywrapcshm_ref (cshm_reff2pywrap, cd_py, na_py,
     & id_py, mt_py)
      external cshm_ref
      integer na_py
      integer id_py
      integer mt_py
      real(kind=8) cd_py(na_py,3)
      real(kind=8) cshm_reff2pywrap
      real(kind=8)  cshm_ref
      cshm_reff2pywrap = cshm_ref(cd_py, na_py, id_py, mt_py)
      end

