/* File: shpmodule.c
 * This file is auto-generated with f2py (version:2.4.2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Mar  9 16:10:15 2026
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *shp_error;
static PyObject *shp_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(shp_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = shp_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_WRAPPEDFUNC(cshm,CSHM)(double*,double*,double*,int*,int*);
extern void F_WRAPPEDFUNC_US(cshm_fix,CSHM_FIX)(double*,double*,double*,int*,int*);
extern void F_WRAPPEDFUNC_US(cshm_ref,CSHM_REF)(double*,double*,int*,int*,int*);
extern void F_FUNC(poly,POLY)(double*,double*,int*,int*,double*,double*);
extern void F_FUNC_US(poly_fix,POLY_FIX)(double*,double*,int*,int*,double*,double*);
extern void F_FUNC_US(poly_ref,POLY_REF)(double*,int*,int*,int*,double*,double*);
extern void F_FUNC(test,TEST)(int*,int*,double*);
extern void F_FUNC(nextline,NEXTLINE)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ cshm ************************************/
static char doc_f2py_rout_shp_cshm[] = "\
cshm = cshm(cd_py,cr_py,mt_py)\n\nWrapper for ``cshm``.\
\n\nParameters\n----------\n"
"cd_py : input rank-2 array('d') with bounds (na_py,3)\n"
"cr_py : input rank-2 array('d') with bounds (na_py,3)\n"
"mt_py : input int\n"
"\nReturns\n-------\n"
"cshm : float";
/* extern void F_WRAPPEDFUNC(cshm,CSHM)(double*,double*,double*,int*,int*); */
static PyObject *f2py_rout_shp_cshm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double cshm = 0;
    double *cd_py = NULL;
    npy_intp cd_py_Dims[2] = {-1, -1};
    const int cd_py_Rank = 2;
    PyArrayObject *capi_cd_py_as_array = NULL;
    int capi_cd_py_intent = 0;
    PyObject *cd_py_capi = Py_None;
    double *cr_py = NULL;
    npy_intp cr_py_Dims[2] = {-1, -1};
    const int cr_py_Rank = 2;
    PyArrayObject *capi_cr_py_as_array = NULL;
    int capi_cr_py_intent = 0;
    PyObject *cr_py_capi = Py_None;
    int na_py = 0;
    int mt_py = 0;
    PyObject *mt_py_capi = Py_None;
    static char *capi_kwlist[] = {"cd_py","cr_py","mt_py",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:shp.cshm",\
        capi_kwlist,&cd_py_capi,&cr_py_capi,&mt_py_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable cd_py */
    cd_py_Dims[1]=3;
    capi_cd_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.cshm: failed to create array from the 1st argument `cd_py`";
    capi_cd_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cd_py_Dims,cd_py_Rank,  capi_cd_py_intent,cd_py_capi,capi_errmess);
    if (capi_cd_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cd_py = (double *)(PyArray_DATA(capi_cd_py_as_array));

    /* Processing variable mt_py */
        f2py_success = int_from_pyobj(&mt_py,mt_py_capi,"shp.cshm() 3rd argument (mt_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable cshm */
    /* Processing variable na_py */
    na_py = shape(cd_py,0);
    CHECKSCALAR(shape(cd_py,0)==na_py,"shape(cd_py,0)==na_py","hidden na_py","cshm:na_py=%d",na_py) {
    /* Processing variable cr_py */
    cr_py_Dims[0]=na_py,cr_py_Dims[1]=3;
    capi_cr_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.cshm: failed to create array from the 2nd argument `cr_py`";
    capi_cr_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cr_py_Dims,cr_py_Rank,  capi_cr_py_intent,cr_py_capi,capi_errmess);
    if (capi_cr_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cr_py = (double *)(PyArray_DATA(capi_cr_py_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&cshm,cd_py,cr_py,&na_py,&mt_py);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",cshm);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_cr_py_as_array!=cr_py_capi) {
        Py_XDECREF(capi_cr_py_as_array); }
    }  /* if (capi_cr_py_as_array == NULL) ... else of cr_py */
    /* End of cleaning variable cr_py */
    } /*CHECKSCALAR(shape(cd_py,0)==na_py)*/
    /* End of cleaning variable na_py */
    /* End of cleaning variable cshm */
    } /*if (f2py_success) of mt_py*/
    /* End of cleaning variable mt_py */
    if((PyObject *)capi_cd_py_as_array!=cd_py_capi) {
        Py_XDECREF(capi_cd_py_as_array); }
    }  /* if (capi_cd_py_as_array == NULL) ... else of cd_py */
    /* End of cleaning variable cd_py */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of cshm ********************************/

/********************************** cshm_fix **********************************/
static char doc_f2py_rout_shp_cshm_fix[] = "\
cshm_fix = cshm_fix(cd_py,cr_py,mt_py)\n\nWrapper for ``cshm_fix``.\
\n\nParameters\n----------\n"
"cd_py : input rank-2 array('d') with bounds (na_py,3)\n"
"cr_py : input rank-2 array('d') with bounds (na_py,3)\n"
"mt_py : input int\n"
"\nReturns\n-------\n"
"cshm_fix : float";
/* extern void F_WRAPPEDFUNC_US(cshm_fix,CSHM_FIX)(double*,double*,double*,int*,int*); */
static PyObject *f2py_rout_shp_cshm_fix(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double cshm_fix = 0;
    double *cd_py = NULL;
    npy_intp cd_py_Dims[2] = {-1, -1};
    const int cd_py_Rank = 2;
    PyArrayObject *capi_cd_py_as_array = NULL;
    int capi_cd_py_intent = 0;
    PyObject *cd_py_capi = Py_None;
    double *cr_py = NULL;
    npy_intp cr_py_Dims[2] = {-1, -1};
    const int cr_py_Rank = 2;
    PyArrayObject *capi_cr_py_as_array = NULL;
    int capi_cr_py_intent = 0;
    PyObject *cr_py_capi = Py_None;
    int na_py = 0;
    int mt_py = 0;
    PyObject *mt_py_capi = Py_None;
    static char *capi_kwlist[] = {"cd_py","cr_py","mt_py",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:shp.cshm_fix",\
        capi_kwlist,&cd_py_capi,&cr_py_capi,&mt_py_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable cd_py */
    cd_py_Dims[1]=3;
    capi_cd_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.cshm_fix: failed to create array from the 1st argument `cd_py`";
    capi_cd_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cd_py_Dims,cd_py_Rank,  capi_cd_py_intent,cd_py_capi,capi_errmess);
    if (capi_cd_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cd_py = (double *)(PyArray_DATA(capi_cd_py_as_array));

    /* Processing variable mt_py */
        f2py_success = int_from_pyobj(&mt_py,mt_py_capi,"shp.cshm_fix() 3rd argument (mt_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable cshm_fix */
    /* Processing variable na_py */
    na_py = shape(cd_py,0);
    CHECKSCALAR(shape(cd_py,0)==na_py,"shape(cd_py,0)==na_py","hidden na_py","cshm_fix:na_py=%d",na_py) {
    /* Processing variable cr_py */
    cr_py_Dims[0]=na_py,cr_py_Dims[1]=3;
    capi_cr_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.cshm_fix: failed to create array from the 2nd argument `cr_py`";
    capi_cr_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cr_py_Dims,cr_py_Rank,  capi_cr_py_intent,cr_py_capi,capi_errmess);
    if (capi_cr_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cr_py = (double *)(PyArray_DATA(capi_cr_py_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&cshm_fix,cd_py,cr_py,&na_py,&mt_py);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",cshm_fix);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_cr_py_as_array!=cr_py_capi) {
        Py_XDECREF(capi_cr_py_as_array); }
    }  /* if (capi_cr_py_as_array == NULL) ... else of cr_py */
    /* End of cleaning variable cr_py */
    } /*CHECKSCALAR(shape(cd_py,0)==na_py)*/
    /* End of cleaning variable na_py */
    /* End of cleaning variable cshm_fix */
    } /*if (f2py_success) of mt_py*/
    /* End of cleaning variable mt_py */
    if((PyObject *)capi_cd_py_as_array!=cd_py_capi) {
        Py_XDECREF(capi_cd_py_as_array); }
    }  /* if (capi_cd_py_as_array == NULL) ... else of cd_py */
    /* End of cleaning variable cd_py */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of cshm_fix ******************************/

/********************************** cshm_ref **********************************/
static char doc_f2py_rout_shp_cshm_ref[] = "\
cshm_ref = cshm_ref(cd_py,id_py,mt_py)\n\nWrapper for ``cshm_ref``.\
\n\nParameters\n----------\n"
"cd_py : input rank-2 array('d') with bounds (na_py,3)\n"
"id_py : input int\n"
"mt_py : input int\n"
"\nReturns\n-------\n"
"cshm_ref : float";
/* extern void F_WRAPPEDFUNC_US(cshm_ref,CSHM_REF)(double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_shp_cshm_ref(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double cshm_ref = 0;
    double *cd_py = NULL;
    npy_intp cd_py_Dims[2] = {-1, -1};
    const int cd_py_Rank = 2;
    PyArrayObject *capi_cd_py_as_array = NULL;
    int capi_cd_py_intent = 0;
    PyObject *cd_py_capi = Py_None;
    int na_py = 0;
    int id_py = 0;
    PyObject *id_py_capi = Py_None;
    int mt_py = 0;
    PyObject *mt_py_capi = Py_None;
    static char *capi_kwlist[] = {"cd_py","id_py","mt_py",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:shp.cshm_ref",\
        capi_kwlist,&cd_py_capi,&id_py_capi,&mt_py_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable cd_py */
    cd_py_Dims[1]=3;
    capi_cd_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.cshm_ref: failed to create array from the 1st argument `cd_py`";
    capi_cd_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cd_py_Dims,cd_py_Rank,  capi_cd_py_intent,cd_py_capi,capi_errmess);
    if (capi_cd_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cd_py = (double *)(PyArray_DATA(capi_cd_py_as_array));

    /* Processing variable mt_py */
        f2py_success = int_from_pyobj(&mt_py,mt_py_capi,"shp.cshm_ref() 3rd argument (mt_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable id_py */
        f2py_success = int_from_pyobj(&id_py,id_py_capi,"shp.cshm_ref() 2nd argument (id_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable cshm_ref */
    /* Processing variable na_py */
    na_py = shape(cd_py,0);
    CHECKSCALAR(shape(cd_py,0)==na_py,"shape(cd_py,0)==na_py","hidden na_py","cshm_ref:na_py=%d",na_py) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&cshm_ref,cd_py,&na_py,&id_py,&mt_py);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",cshm_ref);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(cd_py,0)==na_py)*/
    /* End of cleaning variable na_py */
    /* End of cleaning variable cshm_ref */
    } /*if (f2py_success) of id_py*/
    /* End of cleaning variable id_py */
    } /*if (f2py_success) of mt_py*/
    /* End of cleaning variable mt_py */
    if((PyObject *)capi_cd_py_as_array!=cd_py_capi) {
        Py_XDECREF(capi_cd_py_as_array); }
    }  /* if (capi_cd_py_as_array == NULL) ... else of cd_py */
    /* End of cleaning variable cd_py */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of cshm_ref ******************************/

/************************************ poly ************************************/
static char doc_f2py_rout_shp_poly[] = "\
pl_py,cm_py = poly(cd_py,cr_py,mt_py)\n\nWrapper for ``poly``.\
\n\nParameters\n----------\n"
"cd_py : input rank-2 array('d') with bounds (na_py,3)\n"
"cr_py : input rank-2 array('d') with bounds (na_py,3)\n"
"mt_py : input int\n"
"\nReturns\n-------\n"
"pl_py : rank-2 array('d') with bounds (na_py,3)\n"
"cm_py : float";
/* extern void F_FUNC(poly,POLY)(double*,double*,int*,int*,double*,double*); */
static PyObject *f2py_rout_shp_poly(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *cd_py = NULL;
    npy_intp cd_py_Dims[2] = {-1, -1};
    const int cd_py_Rank = 2;
    PyArrayObject *capi_cd_py_as_array = NULL;
    int capi_cd_py_intent = 0;
    PyObject *cd_py_capi = Py_None;
    double *cr_py = NULL;
    npy_intp cr_py_Dims[2] = {-1, -1};
    const int cr_py_Rank = 2;
    PyArrayObject *capi_cr_py_as_array = NULL;
    int capi_cr_py_intent = 0;
    PyObject *cr_py_capi = Py_None;
    int na_py = 0;
    int mt_py = 0;
    PyObject *mt_py_capi = Py_None;
    double *pl_py = NULL;
    npy_intp pl_py_Dims[2] = {-1, -1};
    const int pl_py_Rank = 2;
    PyArrayObject *capi_pl_py_as_array = NULL;
    int capi_pl_py_intent = 0;
    double cm_py = 0;
    static char *capi_kwlist[] = {"cd_py","cr_py","mt_py",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:shp.poly",\
        capi_kwlist,&cd_py_capi,&cr_py_capi,&mt_py_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable cd_py */
    cd_py_Dims[1]=3;
    capi_cd_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.poly: failed to create array from the 1st argument `cd_py`";
    capi_cd_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cd_py_Dims,cd_py_Rank,  capi_cd_py_intent,cd_py_capi,capi_errmess);
    if (capi_cd_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cd_py = (double *)(PyArray_DATA(capi_cd_py_as_array));

    /* Processing variable mt_py */
        f2py_success = int_from_pyobj(&mt_py,mt_py_capi,"shp.poly() 3rd argument (mt_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable cm_py */
    /* Processing variable na_py */
    na_py = shape(cd_py,0);
    CHECKSCALAR(shape(cd_py,0)==na_py,"shape(cd_py,0)==na_py","hidden na_py","poly:na_py=%d",na_py) {
    /* Processing variable cr_py */
    cr_py_Dims[0]=na_py,cr_py_Dims[1]=3;
    capi_cr_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.poly: failed to create array from the 2nd argument `cr_py`";
    capi_cr_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cr_py_Dims,cr_py_Rank,  capi_cr_py_intent,cr_py_capi,capi_errmess);
    if (capi_cr_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cr_py = (double *)(PyArray_DATA(capi_cr_py_as_array));

    /* Processing variable pl_py */
    pl_py_Dims[0]=na_py,pl_py_Dims[1]=3;
    capi_pl_py_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "shp.shp.poly: failed to create array from the hidden `pl_py`";
    capi_pl_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,pl_py_Dims,pl_py_Rank,  capi_pl_py_intent,Py_None,capi_errmess);
    if (capi_pl_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        pl_py = (double *)(PyArray_DATA(capi_pl_py_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(cd_py,cr_py,&na_py,&mt_py,pl_py,&cm_py);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("Nd",capi_pl_py_as_array,cm_py);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_pl_py_as_array == NULL) ... else of pl_py */
    /* End of cleaning variable pl_py */
    if((PyObject *)capi_cr_py_as_array!=cr_py_capi) {
        Py_XDECREF(capi_cr_py_as_array); }
    }  /* if (capi_cr_py_as_array == NULL) ... else of cr_py */
    /* End of cleaning variable cr_py */
    } /*CHECKSCALAR(shape(cd_py,0)==na_py)*/
    /* End of cleaning variable na_py */
    /* End of cleaning variable cm_py */
    } /*if (f2py_success) of mt_py*/
    /* End of cleaning variable mt_py */
    if((PyObject *)capi_cd_py_as_array!=cd_py_capi) {
        Py_XDECREF(capi_cd_py_as_array); }
    }  /* if (capi_cd_py_as_array == NULL) ... else of cd_py */
    /* End of cleaning variable cd_py */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of poly ********************************/

/********************************** poly_fix **********************************/
static char doc_f2py_rout_shp_poly_fix[] = "\
pl_py,cm_py = poly_fix(cd_py,cr_py,mt_py)\n\nWrapper for ``poly_fix``.\
\n\nParameters\n----------\n"
"cd_py : input rank-2 array('d') with bounds (na_py,3)\n"
"cr_py : input rank-2 array('d') with bounds (na_py,3)\n"
"mt_py : input int\n"
"\nReturns\n-------\n"
"pl_py : rank-2 array('d') with bounds (na_py,3)\n"
"cm_py : float";
/* extern void F_FUNC_US(poly_fix,POLY_FIX)(double*,double*,int*,int*,double*,double*); */
static PyObject *f2py_rout_shp_poly_fix(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *cd_py = NULL;
    npy_intp cd_py_Dims[2] = {-1, -1};
    const int cd_py_Rank = 2;
    PyArrayObject *capi_cd_py_as_array = NULL;
    int capi_cd_py_intent = 0;
    PyObject *cd_py_capi = Py_None;
    double *cr_py = NULL;
    npy_intp cr_py_Dims[2] = {-1, -1};
    const int cr_py_Rank = 2;
    PyArrayObject *capi_cr_py_as_array = NULL;
    int capi_cr_py_intent = 0;
    PyObject *cr_py_capi = Py_None;
    int na_py = 0;
    int mt_py = 0;
    PyObject *mt_py_capi = Py_None;
    double *pl_py = NULL;
    npy_intp pl_py_Dims[2] = {-1, -1};
    const int pl_py_Rank = 2;
    PyArrayObject *capi_pl_py_as_array = NULL;
    int capi_pl_py_intent = 0;
    double cm_py = 0;
    static char *capi_kwlist[] = {"cd_py","cr_py","mt_py",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:shp.poly_fix",\
        capi_kwlist,&cd_py_capi,&cr_py_capi,&mt_py_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable cd_py */
    cd_py_Dims[1]=3;
    capi_cd_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.poly_fix: failed to create array from the 1st argument `cd_py`";
    capi_cd_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cd_py_Dims,cd_py_Rank,  capi_cd_py_intent,cd_py_capi,capi_errmess);
    if (capi_cd_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cd_py = (double *)(PyArray_DATA(capi_cd_py_as_array));

    /* Processing variable mt_py */
        f2py_success = int_from_pyobj(&mt_py,mt_py_capi,"shp.poly_fix() 3rd argument (mt_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable cm_py */
    /* Processing variable na_py */
    na_py = shape(cd_py,0);
    CHECKSCALAR(shape(cd_py,0)==na_py,"shape(cd_py,0)==na_py","hidden na_py","poly_fix:na_py=%d",na_py) {
    /* Processing variable cr_py */
    cr_py_Dims[0]=na_py,cr_py_Dims[1]=3;
    capi_cr_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.poly_fix: failed to create array from the 2nd argument `cr_py`";
    capi_cr_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cr_py_Dims,cr_py_Rank,  capi_cr_py_intent,cr_py_capi,capi_errmess);
    if (capi_cr_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cr_py = (double *)(PyArray_DATA(capi_cr_py_as_array));

    /* Processing variable pl_py */
    pl_py_Dims[0]=na_py,pl_py_Dims[1]=3;
    capi_pl_py_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "shp.shp.poly_fix: failed to create array from the hidden `pl_py`";
    capi_pl_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,pl_py_Dims,pl_py_Rank,  capi_pl_py_intent,Py_None,capi_errmess);
    if (capi_pl_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        pl_py = (double *)(PyArray_DATA(capi_pl_py_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(cd_py,cr_py,&na_py,&mt_py,pl_py,&cm_py);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("Nd",capi_pl_py_as_array,cm_py);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_pl_py_as_array == NULL) ... else of pl_py */
    /* End of cleaning variable pl_py */
    if((PyObject *)capi_cr_py_as_array!=cr_py_capi) {
        Py_XDECREF(capi_cr_py_as_array); }
    }  /* if (capi_cr_py_as_array == NULL) ... else of cr_py */
    /* End of cleaning variable cr_py */
    } /*CHECKSCALAR(shape(cd_py,0)==na_py)*/
    /* End of cleaning variable na_py */
    /* End of cleaning variable cm_py */
    } /*if (f2py_success) of mt_py*/
    /* End of cleaning variable mt_py */
    if((PyObject *)capi_cd_py_as_array!=cd_py_capi) {
        Py_XDECREF(capi_cd_py_as_array); }
    }  /* if (capi_cd_py_as_array == NULL) ... else of cd_py */
    /* End of cleaning variable cd_py */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of poly_fix ******************************/

/********************************** poly_ref **********************************/
static char doc_f2py_rout_shp_poly_ref[] = "\
pl_py,cm_py = poly_ref(cd_py,id_py,mt_py)\n\nWrapper for ``poly_ref``.\
\n\nParameters\n----------\n"
"cd_py : input rank-2 array('d') with bounds (na_py,3)\n"
"id_py : input int\n"
"mt_py : input int\n"
"\nReturns\n-------\n"
"pl_py : rank-2 array('d') with bounds (na_py,3)\n"
"cm_py : float";
/* extern void F_FUNC_US(poly_ref,POLY_REF)(double*,int*,int*,int*,double*,double*); */
static PyObject *f2py_rout_shp_poly_ref(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *cd_py = NULL;
    npy_intp cd_py_Dims[2] = {-1, -1};
    const int cd_py_Rank = 2;
    PyArrayObject *capi_cd_py_as_array = NULL;
    int capi_cd_py_intent = 0;
    PyObject *cd_py_capi = Py_None;
    int na_py = 0;
    int id_py = 0;
    PyObject *id_py_capi = Py_None;
    int mt_py = 0;
    PyObject *mt_py_capi = Py_None;
    double *pl_py = NULL;
    npy_intp pl_py_Dims[2] = {-1, -1};
    const int pl_py_Rank = 2;
    PyArrayObject *capi_pl_py_as_array = NULL;
    int capi_pl_py_intent = 0;
    double cm_py = 0;
    static char *capi_kwlist[] = {"cd_py","id_py","mt_py",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:shp.poly_ref",\
        capi_kwlist,&cd_py_capi,&id_py_capi,&mt_py_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable cd_py */
    cd_py_Dims[1]=3;
    capi_cd_py_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "shp.shp.poly_ref: failed to create array from the 1st argument `cd_py`";
    capi_cd_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cd_py_Dims,cd_py_Rank,  capi_cd_py_intent,cd_py_capi,capi_errmess);
    if (capi_cd_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cd_py = (double *)(PyArray_DATA(capi_cd_py_as_array));

    /* Processing variable mt_py */
        f2py_success = int_from_pyobj(&mt_py,mt_py_capi,"shp.poly_ref() 3rd argument (mt_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable id_py */
        f2py_success = int_from_pyobj(&id_py,id_py_capi,"shp.poly_ref() 2nd argument (id_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable cm_py */
    /* Processing variable na_py */
    na_py = shape(cd_py,0);
    CHECKSCALAR(shape(cd_py,0)==na_py,"shape(cd_py,0)==na_py","hidden na_py","poly_ref:na_py=%d",na_py) {
    /* Processing variable pl_py */
    pl_py_Dims[0]=na_py,pl_py_Dims[1]=3;
    capi_pl_py_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "shp.shp.poly_ref: failed to create array from the hidden `pl_py`";
    capi_pl_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,pl_py_Dims,pl_py_Rank,  capi_pl_py_intent,Py_None,capi_errmess);
    if (capi_pl_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        pl_py = (double *)(PyArray_DATA(capi_pl_py_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(cd_py,&na_py,&id_py,&mt_py,pl_py,&cm_py);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("Nd",capi_pl_py_as_array,cm_py);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_pl_py_as_array == NULL) ... else of pl_py */
    /* End of cleaning variable pl_py */
    } /*CHECKSCALAR(shape(cd_py,0)==na_py)*/
    /* End of cleaning variable na_py */
    /* End of cleaning variable cm_py */
    } /*if (f2py_success) of id_py*/
    /* End of cleaning variable id_py */
    } /*if (f2py_success) of mt_py*/
    /* End of cleaning variable mt_py */
    if((PyObject *)capi_cd_py_as_array!=cd_py_capi) {
        Py_XDECREF(capi_cd_py_as_array); }
    }  /* if (capi_cd_py_as_array == NULL) ... else of cd_py */
    /* End of cleaning variable cd_py */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of poly_ref ******************************/

/************************************ test ************************************/
static char doc_f2py_rout_shp_test[] = "\
pl_py = test(nl_py,id_py)\n\nWrapper for ``test``.\
\n\nParameters\n----------\n"
"nl_py : input int\n"
"id_py : input int\n"
"\nReturns\n-------\n"
"pl_py : rank-2 array('d') with bounds (1 + nl_py,3)";
/* extern void F_FUNC(test,TEST)(int*,int*,double*); */
static PyObject *f2py_rout_shp_test(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int nl_py = 0;
    PyObject *nl_py_capi = Py_None;
    int id_py = 0;
    PyObject *id_py_capi = Py_None;
    double *pl_py = NULL;
    npy_intp pl_py_Dims[2] = {-1, -1};
    const int pl_py_Rank = 2;
    PyArrayObject *capi_pl_py_as_array = NULL;
    int capi_pl_py_intent = 0;
    static char *capi_kwlist[] = {"nl_py","id_py",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:shp.test",\
        capi_kwlist,&nl_py_capi,&id_py_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable nl_py */
        f2py_success = int_from_pyobj(&nl_py,nl_py_capi,"shp.test() 1st argument (nl_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable id_py */
        f2py_success = int_from_pyobj(&id_py,id_py_capi,"shp.test() 2nd argument (id_py) can't be converted to int");
    if (f2py_success) {
    /* Processing variable pl_py */
    pl_py_Dims[0]=1 + nl_py,pl_py_Dims[1]=3;
    capi_pl_py_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "shp.shp.test: failed to create array from the hidden `pl_py`";
    capi_pl_py_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,pl_py_Dims,pl_py_Rank,  capi_pl_py_intent,Py_None,capi_errmess);
    if (capi_pl_py_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = shp_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        pl_py = (double *)(PyArray_DATA(capi_pl_py_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&nl_py,&id_py,pl_py);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_pl_py_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_pl_py_as_array == NULL) ... else of pl_py */
    /* End of cleaning variable pl_py */
    } /*if (f2py_success) of id_py*/
    /* End of cleaning variable id_py */
    } /*if (f2py_success) of nl_py*/
    /* End of cleaning variable nl_py */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of test ********************************/

/********************************** nextline **********************************/
static char doc_f2py_rout_shp_nextline[] = "\
nextline(iunit)\n\nWrapper for ``nextline``.\
\n\nParameters\n----------\n"
"iunit : input int";
/* extern void F_FUNC(nextline,NEXTLINE)(int*); */
static PyObject *f2py_rout_shp_nextline(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int iunit = 0;
    PyObject *iunit_capi = Py_None;
    static char *capi_kwlist[] = {"iunit",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:shp.nextline",\
        capi_kwlist,&iunit_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable iunit */
        f2py_success = int_from_pyobj(&iunit,iunit_capi,"shp.nextline() 1st argument (iunit) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&iunit);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of iunit*/
    /* End of cleaning variable iunit */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of nextline ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"cshm",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC(cshm,CSHM),  (f2py_init_func)f2py_rout_shp_cshm,doc_f2py_rout_shp_cshm},
    {"cshm_fix",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC_US(cshm_fix,CSHM_FIX),  (f2py_init_func)f2py_rout_shp_cshm_fix,doc_f2py_rout_shp_cshm_fix},
    {"cshm_ref",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC_US(cshm_ref,CSHM_REF),  (f2py_init_func)f2py_rout_shp_cshm_ref,doc_f2py_rout_shp_cshm_ref},
    {"poly",-1,{{-1}},0,0,(char *)  F_FUNC(poly,POLY),  (f2py_init_func)f2py_rout_shp_poly,doc_f2py_rout_shp_poly},
    {"poly_fix",-1,{{-1}},0,0,(char *)  F_FUNC_US(poly_fix,POLY_FIX),  (f2py_init_func)f2py_rout_shp_poly_fix,doc_f2py_rout_shp_poly_fix},
    {"poly_ref",-1,{{-1}},0,0,(char *)  F_FUNC_US(poly_ref,POLY_REF),  (f2py_init_func)f2py_rout_shp_poly_ref,doc_f2py_rout_shp_poly_ref},
    {"test",-1,{{-1}},0,0,(char *)  F_FUNC(test,TEST),  (f2py_init_func)f2py_rout_shp_test,doc_f2py_rout_shp_test},
    {"nextline",-1,{{-1}},0,0,(char *)  F_FUNC(nextline,NEXTLINE),  (f2py_init_func)f2py_rout_shp_nextline,doc_f2py_rout_shp_nextline},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "shp",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_shp(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = shp_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module shp (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.4.2");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'shp' is auto-generated with f2py (version:2.4.2).\nFunctions:\n"
"    cshm = cshm(cd_py,cr_py,mt_py)\n"
"    cshm_fix = cshm_fix(cd_py,cr_py,mt_py)\n"
"    cshm_ref = cshm_ref(cd_py,id_py,mt_py)\n"
"    pl_py,cm_py = poly(cd_py,cr_py,mt_py)\n"
"    pl_py,cm_py = poly_fix(cd_py,cr_py,mt_py)\n"
"    pl_py,cm_py = poly_ref(cd_py,id_py,mt_py)\n"
"    pl_py = test(nl_py,id_py)\n"
"    nextline(iunit)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.4.2");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    shp_error = PyErr_NewException ("shp.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_shp_error", shp_error);
    Py_DECREF(shp_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

    {
      extern double F_FUNC(cshm,CSHM)(void);
      PyObject* o = PyDict_GetItemString(d,"cshm");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_WRAPPEDFUNC(cshm,CSHM),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("cshm");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

    {
      extern double F_FUNC_US(cshm_fix,CSHM_FIX)(void);
      PyObject* o = PyDict_GetItemString(d,"cshm_fix");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_WRAPPEDFUNC_US(cshm_fix,CSHM_FIX),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("cshm_fix");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

    {
      extern double F_FUNC_US(cshm_ref,CSHM_REF)(void);
      PyObject* o = PyDict_GetItemString(d,"cshm_ref");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_WRAPPEDFUNC_US(cshm_ref,CSHM_REF),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("cshm_ref");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    





/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"shp");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
